spring:
  application:
    name: kafka-producer
    #through java config
#Kafka:
#    bootstrap-servers : localhost:9092
#    topic :
#      driver-location : driver-location-updates-with-2-partitions
#      partitions : 2


  kafka:
    bootstrap-servers: localhost:9092

    producer:
      topic:
        driver-location : driver-location-updates-with-2-partitions
        partitions : 2
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        linger.ms: 5